#!/usr/bin/env bash
# install_ui.sh — write a host-side `lexichron-ui` command for this image.
#
# Runs INSIDE the image (apptainer run --app install-ui lexichron.sif) and
# writes two files into the user's home directory, which is bind-mounted:
#   ~/.lexichron/host_bridge.sh   the Slurm helper, copied out of the image
#   ~/.local/bin/lexichron-ui     starts the helper and the UI together
#
# Options:
#   --bin DIR      where to put the command (default ~/.local/bin)
#   --bind DIR     extra host directory to bind at run time (repeatable)
set -euo pipefail

BIN_DIR="$HOME/.local/bin"
EXTRA_BINDS=()
while [ $# -gt 0 ]; do
    case "$1" in
        --bin)  BIN_DIR="$2"; shift 2 ;;
        --bind) EXTRA_BINDS+=("$2"); shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

IMAGE="${APPTAINER_CONTAINER:-${SINGULARITY_CONTAINER:-}}"
[ -n "$IMAGE" ] || { echo "Error: run this inside the image: apptainer run --app install-ui lexichron.sif"; exit 1; }

STATE_DIR="$HOME/.lexichron"
mkdir -p "$STATE_DIR" "$BIN_DIR"
cp /opt/lexichron/host_bridge.sh "$STATE_DIR/host_bridge.sh"
chmod 755 "$STATE_DIR/host_bridge.sh"

# Same bind logic as register_kernel.sh: skip what the site already binds.
MOUNTS="$(awk '{print $2}' /proc/mounts)"
SYSTEM_BOUND=""
CANDIDATES=""
for d in /scratch /vast /gpfs /work /project /projects /data "${EXTRA_BINDS[@]}"; do
    case " $CANDIDATES " in *" $d "*) continue ;; esac
    CANDIDATES="$CANDIDATES $d"
    p="$d"
    while [ "$p" != "/" ]; do
        if printf '%s\n' "$MOUNTS" | grep -qx "$p"; then SYSTEM_BOUND="$SYSTEM_BOUND $d"; break; fi
        p="$(dirname "$p")"
    done
done

cat > "$BIN_DIR/lexichron-ui" <<LAUNCHER
#!/usr/bin/env bash
# Generated by lexichron install-ui. Starts the Slurm host bridge and the
# lexichron terminal UI inside the image. Usage: lexichron-ui [lexichron.yaml]
set -u
img=$(printf '%q' "$IMAGE")
BRIDGE_DIR="\$HOME/.lexichron/bridge"
mkdir -p "\$BRIDGE_DIR"
bash "\$HOME/.lexichron/host_bridge.sh" "\$BRIDGE_DIR" &
BRIDGE_PID=\$!
trap 'touch "\$BRIDGE_DIR/stop"; kill \$BRIDGE_PID 2>/dev/null' EXIT
binds=""
for d in${CANDIDATES}; do
  case " ${SYSTEM_BOUND} " in *" \$d "*) continue ;; esac
  [ -d "\$d" ] && binds="\$binds --bind \$d"
done
# (no exec: the EXIT trap above must run to stop the bridge)
apptainer exec \$binds --env LEXICHRON_BRIDGE_DIR="\$BRIDGE_DIR" "\$img" lexichron ui "\$@"
exit \$?
LAUNCHER
chmod 755 "$BIN_DIR/lexichron-ui"

echo "Installed $BIN_DIR/lexichron-ui (image: $IMAGE)"
case ":$PATH:" in
    *":$BIN_DIR:"*) echo "Run it with:  lexichron-ui" ;;
    *) echo "Note: $BIN_DIR is not on your PATH. Run it as $BIN_DIR/lexichron-ui, or add"
       echo "      export PATH=\"$BIN_DIR:\$PATH\"   to your ~/.bashrc" ;;
esac
