#!/usr/bin/env bash
# install_ui.sh — write host-side `lexichron` and `lexichron-ui` commands for
# this image. (App names: `install` and, for compatibility, `install-ui`.)
#
# Runs INSIDE the image (apptainer run --app install lexichron.sif) and writes
# into the user's home directory, which is bind-mounted:
#   ~/.lexichron/host_bridge.sh   the Slurm helper, copied out of the image
#   ~/.local/bin/lexichron        runs any lexichron command inside the image
#   ~/.local/bin/lexichron-ui     starts the Slurm helper and the terminal UI
#
# Both commands re-pull the image if its file has disappeared (scratch
# filesystems get purged), using the registry reference recorded at install.
#
# Options:
#   --bin DIR        where to put the commands (default ~/.local/bin)
#   --bind DIR       extra host directory to bind at run time (repeatable)
#   --ref REF        registry reference for re-pulls, e.g.
#                    ghcr.io/eric-d-knowles/lexichron:0.1.0 (default: derived
#                    from the image file name)
#   --tmpdir DIR     APPTAINER_TMPDIR to use for pulls (default: beside the image)
#   --cachedir DIR   APPTAINER_CACHEDIR to use for pulls (default: beside the image)
set -euo pipefail

BIN_DIR="$HOME/.local/bin"
EXTRA_BINDS=()
REF=""
TMPDIR_OPT=""
CACHEDIR_OPT=""
while [ $# -gt 0 ]; do
    case "$1" in
        --bin)      BIN_DIR="$2"; shift 2 ;;
        --bind)     EXTRA_BINDS+=("$2"); shift 2 ;;
        --ref)      REF="$2"; shift 2 ;;
        --tmpdir)   TMPDIR_OPT="$2"; shift 2 ;;
        --cachedir) CACHEDIR_OPT="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

IMAGE="${APPTAINER_CONTAINER:-${SINGULARITY_CONTAINER:-}}"
[ -n "$IMAGE" ] || { echo "Error: run this inside the image: apptainer run --app install lexichron.sif"; exit 1; }
IMAGE_DIR="$(dirname "$IMAGE")"

if [ -z "$REF" ]; then
    # lexichron-0.1.0.sif -> ghcr.io/eric-d-knowles/lexichron:0.1.0
    base="$(basename "$IMAGE" .sif)"
    ver="${base#lexichron-}"
    [ "$ver" = "$base" ] && ver="latest"
    REF="ghcr.io/eric-d-knowles/lexichron:${ver}"
fi
[ -n "$TMPDIR_OPT" ]   || TMPDIR_OPT="$IMAGE_DIR/apptainer-tmp"
[ -n "$CACHEDIR_OPT" ] || CACHEDIR_OPT="$IMAGE_DIR/apptainer-cache"

STATE_DIR="$HOME/.lexichron"
mkdir -p "$STATE_DIR" "$BIN_DIR"
cp /opt/lexichron/host_bridge.sh "$STATE_DIR/host_bridge.sh"
chmod 755 "$STATE_DIR/host_bridge.sh"

# Same bind logic as register_kernel.sh: skip what the site already binds.
MOUNTS="$(awk '{print $2}' /proc/mounts)"
SYSTEM_BOUND=""
CANDIDATES=""
for d in /scratch /vast /gpfs /work /project /projects /data "${EXTRA_BINDS[@]}"; do
    case " $CANDIDATES " in *" $d "*) continue ;; esac
    CANDIDATES="$CANDIDATES $d"
    p="$d"
    while [ "$p" != "/" ]; do
        if printf '%s\n' "$MOUNTS" | grep -qx "$p"; then SYSTEM_BOUND="$SYSTEM_BOUND $d"; break; fi
        p="$(dirname "$p")"
    done
done

# Shared prelude for both commands: locate (or re-pull) the image, set binds.
PRELUDE="$(cat <<PRE
img=$(printf '%q' "$IMAGE")
ref=$(printf '%q' "$REF")
export APPTAINER_TMPDIR=$(printf '%q' "$TMPDIR_OPT")
export APPTAINER_CACHEDIR=$(printf '%q' "$CACHEDIR_OPT")
if ! command -v apptainer >/dev/null 2>&1; then
  echo "lexichron: 'apptainer' not found; try: module load apptainer" >&2; exit 127
fi
if [ ! -f "\$img" ]; then
  echo "lexichron: image \$img is missing (purged?); pulling oras://\$ref ..." >&2
  mkdir -p "\$(dirname "\$img")" "\$APPTAINER_TMPDIR" "\$APPTAINER_CACHEDIR"
  apptainer pull "\$img" "oras://\$ref" || exit 1
fi
binds=""
for d in${CANDIDATES}; do
  case " ${SYSTEM_BOUND} " in *" \$d "*) continue ;; esac
  [ -d "\$d" ] && binds="\$binds --bind \$d"
done
PRE
)"

cat > "$BIN_DIR/lexichron" <<LAUNCHER
#!/usr/bin/env bash
# Generated by lexichron install. Runs a lexichron command inside the image:
#   lexichron acquire lexichron.yaml      lexichron --help
set -u
$PRELUDE
exec apptainer exec \$binds "\$img" lexichron "\$@"
LAUNCHER
chmod 755 "$BIN_DIR/lexichron"

cat > "$BIN_DIR/lexichron-ui" <<LAUNCHER
#!/usr/bin/env bash
# Generated by lexichron install. Starts the Slurm host helper and the
# lexichron terminal UI inside the image. Usage: lexichron-ui [lexichron.yaml]
set -u
$PRELUDE
BRIDGE_DIR="\$HOME/.lexichron/bridge"
mkdir -p "\$BRIDGE_DIR"
bash "\$HOME/.lexichron/host_bridge.sh" "\$BRIDGE_DIR" &
BRIDGE_PID=\$!
trap 'touch "\$BRIDGE_DIR/stop"; kill \$BRIDGE_PID 2>/dev/null' EXIT
# (no exec: the EXIT trap above must run to stop the helper)
apptainer exec \$binds --env LEXICHRON_BRIDGE_DIR="\$BRIDGE_DIR" "\$img" lexichron ui "\$@"
exit \$?
LAUNCHER
chmod 755 "$BIN_DIR/lexichron-ui"

echo "Installed $BIN_DIR/lexichron and $BIN_DIR/lexichron-ui"
echo "  image: $IMAGE"
echo "  re-pull reference: oras://$REF"
case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "Note: $BIN_DIR is not on your PATH; add this to ~/.bashrc:"
       echo "      export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac
